version: '3'

services:
  web:
    container_name: PHT_Frontend_Dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=dev